services:
  gateway:
    container_name: ms_gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - users
    env_file:
      - ./gateway/.env
    networks:
      - gateway_network
      - users_network
    volumes:
      - ./gateway_data:/app
    restart: unless-stopped

  users:
    container_name: ms_users
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./users/.env
    networks:
      - users_network
      - gateway_network
      - db_network
    volumes:
      - ./users_data:/app
    restart: unless-stopped

  # alloy:
  #   image: grafana/alloy:latest
  #   container_name: alloy
  #   user: root
  #   volumes:
  #     - ./alloy/:/etc/alloy/
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #   networks:
  #     - grafana
  #     - db_network
  #   restart: unless-stopped
  #   command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "12345:12345"
  #     - "4317:4317"
  #     - "4318:4318"
  #   depends_on:
  #     - loki
  #     - prometheus

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki:/etc/loki/
      - loki_data:/loki/
    ports:
      - "3100:3100"
    networks:
      - grafana
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    user: "0:0"
    ports:
      - "5678:5678"
    environment:
      - ./.env
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - n8n 
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - grafana
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    shm_size: 512mb
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pg_db_data:/var/lib/postgresql/data
    networks:
      db_network:
        ipv4_address: 10.5.0.10
      grafana:
      users_network:
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webdevuser -d vinted_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus/
    command:
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=1d'
      - '--storage.tsdb.retention.size=512MB'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - grafana
    restart: always

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    depends_on:
      - prometheus
      - loki
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    networks:
      - grafana
      - db_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false  
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - grafana
      - elascticsearch_network
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elascticsearch_network
    restart: always

  redis:
    image: redis:7-alpine
    container_name: fake-vinted-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  loki_data:
  n8n_data:
  pg_db_data:
  elasticsearch_data:
  grafana_data:
  prometheus_data:
  redis_data:
  gateway_data:
  users_data:

networks:
  gateway_network:
    driver: bridge
  users_network:
    driver: bridge
  n8n:
    driver: bridge
  grafana:
    driver: bridge
  elascticsearch_network:
    driver: bridge
  db_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1