user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    limit_req_zone $binary_remote_addr zone=api:10m rate=10000r/m;
    limit_req_zone $binary_remote_addr zone=auth:10m rate=1000r/m;

    include /etc/nginx/conf.d/*.conf;
}